
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action NuevaVistaAction;
	private global::Gtk.Action CategoriasAction;
	private global::Gtk.Action ArtculosAction;
	private global::Gtk.Action addAction;
	private global::Gtk.Action refreshAction;
	private global::Gtk.Action editAction;
	private global::Gtk.Action deleteAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.Notebook myNotebook;
	private global::Gtk.Toolbar toolbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.NuevaVistaAction = new global::Gtk.Action ("NuevaVistaAction", global::Mono.Unix.Catalog.GetString ("Nueva vista"), null, null);
		this.NuevaVistaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Nueva vista");
		w1.Add (this.NuevaVistaAction, null);
		this.CategoriasAction = new global::Gtk.Action ("CategoriasAction", global::Mono.Unix.Catalog.GetString ("Categorias"), null, null);
		this.CategoriasAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Categorias");
		w1.Add (this.CategoriasAction, null);
		this.ArtculosAction = new global::Gtk.Action ("ArtculosAction", global::Mono.Unix.Catalog.GetString ("Artículos"), null, null);
		this.ArtculosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Artículos");
		w1.Add (this.ArtculosAction, null);
		this.addAction = new global::Gtk.Action ("addAction", null, null, "gtk-add");
		w1.Add (this.addAction, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.editAction = new global::Gtk.Action ("editAction", null, null, "gtk-edit");
		w1.Add (this.editAction, null);
		this.deleteAction = new global::Gtk.Action ("deleteAction", null, null, "gtk-delete");
		w1.Add (this.deleteAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='NuevaVistaAction' action='NuevaVistaAction'><menuitem name='CategoriasAction' action='CategoriasAction'/><menuitem name='ArtculosAction' action='ArtculosAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.myNotebook = new global::Gtk.Notebook ();
		this.myNotebook.CanFocus = true;
		this.myNotebook.Name = "myNotebook";
		this.myNotebook.CurrentPage = 0;
		this.vbox1.Add (this.myNotebook);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.myNotebook]));
		w3.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='addAction' action='addAction'/><toolitem name='refreshAction' action='refreshAction'/><toolitem name='editAction' action='editAction'/><toolitem name='deleteAction' action='deleteAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox1.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar1]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
